import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const allowed=["https://kovalenkoserhii2107-maker.github.io","http://localhost:5173","http://127.0.0.1:5173"];
const headers=(origin:string|null)=>({"Access-Control-Allow-Origin":allowed.includes(origin||"")?origin!:allowed[0],"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json","Vary":"Origin"});
const zero={treasury:0,people:0,elite:0,security:0,diplomacy:0};
const demos=[
  {chapter:"Глава I",kicker:"Утро в резиденции",title:"Цена спокойствия",text:"Союз портовых городов предлагает республике дешёвое зерно. Взамен он требует исключительного права пользоваться Восточной гаванью десять лет. Министр финансов называет соглашение спасением, а глава торговой палаты — медленной потерей независимости.",speaker:"Мира Вельская",role:"министр финансов",choices:[{id:"sign",label:"Подписать соглашение",hint:"Казна получит передышку, но соседи усилят влияние"},{id:"refuse",label:"Отказать союзу",hint:"Сохраним контроль над портом, рискуя ростом цен"},{id:"auction",label:"Объявить открытый конкурс",hint:"Медленнее, зато условия будут прозрачнее"}]},
  {chapter:"Глава II",kicker:"Полдень · Совет министров",title:"Город без света",text:"Старая электростанция остановилась, и северные кварталы живут по графику отключений. Частная компания готова восстановить её за неделю, если государство гарантирует тариф на пять лет. Инженеры предлагают более долгий государственный ремонт.",speaker:"Теодор Марен",role:"министр инфраструктуры",choices:[{id:"private",label:"Принять условия компании",hint:"Быстрое решение с долгосрочной ценой"},{id:"public",label:"Ремонтировать силами государства",hint:"Дешевле в будущем, но кризис затянется"},{id:"ration",label:"Перераспределить энергию",hint:"Выиграем время за счёт промышленности"}]},
  {chapter:"Глава III",kicker:"Вечер · Закрытое заседание",title:"Письмо губернаторов",text:"Три губернатора требуют оставить больше налогов регионам. Они обещают совместно поддержать вашу реформу образования, но центральное правительство потеряет часть доходов и контроля.",speaker:"Леон Арден",role:"глава администрации",choices:[{id:"accept",label:"Согласиться на автономию",hint:"Регионы поддержат реформы"},{id:"deny",label:"Сохранить прежний порядок",hint:"Центр останется сильным"},{id:"pilot",label:"Провести пилот в одном регионе",hint:"Осторожный компромисс вызовет ревность остальных"}]},
];

function demo(body:any){const turn=Math.max(1,Number(body.turn)||1),choice=body.choice;const scene=demos[turn%demos.length];if(!choice)return{mode:"demo",consequence:{headline:"",text:"",newspaper:""},scene:demos[0],changes:zero,threads:["Переговоры о Восточной гавани"]};const maps:Record<string,any>={sign:{treasury:9,people:3,elite:2,security:0,diplomacy:-7},refuse:{treasury:-6,people:-4,elite:4,security:2,diplomacy:5},auction:{treasury:-2,people:5,elite:-3,security:0,diplomacy:2},private:{treasury:-3,people:7,elite:6,security:2,diplomacy:0},public:{treasury:-8,people:1,elite:-4,security:-2,diplomacy:0},ration:{treasury:3,people:-5,elite:-5,security:1,diplomacy:0},accept:{treasury:-7,people:5,elite:7,security:-4,diplomacy:0},deny:{treasury:4,people:-4,elite:-6,security:5,diplomacy:0},pilot:{treasury:-2,people:2,elite:1,security:1,diplomacy:0}};return{mode:"demo",consequence:{headline:"Решение принято",text:`Совет зафиксировал ваше решение: «${choice.label}». Первые сторонники уже называют его прагматичным, противники готовят публичный ответ. Настоящие последствия проявятся в следующих главах.`,newspaper:`Президент сделал выбор. Республика ждёт, какую цену придётся заплатить.`},scene,changes:maps[choice.id]||zero,threads:[...(body.threads||[]).slice(-4),`Последствия решения «${choice.label}»`]}}

const schema={type:"object",additionalProperties:false,required:["consequence","scene","changes","threads"],properties:{consequence:{type:"object",additionalProperties:false,required:["headline","text","newspaper"],properties:{headline:{type:"string"},text:{type:"string"},newspaper:{type:"string"}}},scene:{type:"object",additionalProperties:false,required:["chapter","kicker","title","text","speaker","role","choices"],properties:{chapter:{type:"string"},kicker:{type:"string"},title:{type:"string"},text:{type:"string"},speaker:{type:"string"},role:{type:"string"},choices:{type:"array",minItems:3,maxItems:3,items:{type:"object",additionalProperties:false,required:["id","label","hint"],properties:{id:{type:"string"},label:{type:"string"},hint:{type:"string"}}}}}},changes:{type:"object",additionalProperties:false,required:["treasury","people","elite","security","diplomacy"],properties:{treasury:{type:"integer",minimum:-12,maximum:12},people:{type:"integer",minimum:-12,maximum:12},elite:{type:"integer",minimum:-12,maximum:12},security:{type:"integer",minimum:-12,maximum:12},diplomacy:{type:"integer",minimum:-12,maximum:12}}},threads:{type:"array",maxItems:8,items:{type:"string"}}}};

async function requestIdentifier(req:Request){
  const forwarded=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim();
  const address=req.headers.get("cf-connecting-ip")||forwarded||req.headers.get("x-real-ip")||"unknown";
  const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`chronicles:${address}`));
  return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,"0")).join("");
}

async function checkRateLimit(req:Request){
  const url=Deno.env.get("SUPABASE_URL");
  const legacy=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  let secret=legacy;
  try{const keys=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}");secret=keys.default||Object.values(keys)[0]||legacy}catch{/* legacy fallback */}
  if(!url||typeof secret!=="string")throw new Error("Rate limiter is not configured");
  const response=await fetch(`${url}/rest/v1/rpc/check_story_rate_limit`,{method:"POST",headers:{apikey:secret,Authorization:`Bearer ${secret}`,"Content-Type":"application/json"},body:JSON.stringify({p_identifier:await requestIdentifier(req)})});
  if(!response.ok)throw new Error(`Rate limiter ${response.status}`);
  const [result]=await response.json();
  return result as {is_allowed:boolean;retry_after_seconds:number;remaining_today:number};
}

Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response("ok",{headers:headers(origin)});if(req.method!=="POST")return new Response(JSON.stringify({error:"Method not allowed"}),{status:405,headers:headers(origin)});try{const body=await req.json();if(JSON.stringify(body).length>24000)throw new Error("История слишком велика");const key=Deno.env.get("OPENAI_API_KEY");if(!key)return new Response(JSON.stringify(demo(body)),{headers:headers(origin)});const limit=await checkRateLimit(req);if(!limit.is_allowed)return new Response(JSON.stringify({error:"Лимит решений временно исчерпан. Попробуйте позже.",code:"rate_limited"}),{status:429,headers:{...headers(origin),"Retry-After":String(limit.retry_after_seconds)}});
  const prompt=`Ты — игровой режиссёр политической драмы 13+ «Хроники власти». Мир полностью вымышлен. Игрок — президент небольшой Черноморской Республики. Создавай сложные, но понятные моральные и управленческие дилеммы без единственно правильного ответа. Продолжай незавершённые линии и заставляй старые решения возвращаться. Не используй реальные действующие партии и политиков. Без эротики, натуралистического насилия, самоповреждений и азартных игр. Каждая сцена: 90–140 слов, ровно 3 существенно разных решения. Последствие: 50–90 слов. Изменения показателей должны логично соответствовать выбору и лежать от -12 до 12. Верни также до 8 кратких активных сюжетных линий.`;
  const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:Deno.env.get("OPENAI_MODEL")||"gpt-5.4-mini",store:false,instructions:prompt,input:JSON.stringify(body),max_output_tokens:1400,text:{format:{type:"json_schema",name:"game_turn",strict:true,schema}}})});if(!response.ok)throw new Error(`OpenAI ${response.status}: ${await response.text()}`);const data=await response.json();
  const outputText=data.output_text??data.output?.flatMap((item:any)=>item.content??[]).find((content:any)=>content.type==="output_text")?.text;
  if(typeof outputText!=="string"||!outputText.trim())throw new Error(`OpenAI не вернул текст сцены (status: ${data.status??"unknown"})`);
  const parsed=JSON.parse(outputText);return new Response(JSON.stringify({mode:"ai",...parsed}),{headers:headers(origin)});
}catch(error){console.error(error);return new Response(JSON.stringify({error:error instanceof Error?error.message:"Unknown error"}),{status:400,headers:headers(origin)})}});
